ARG NGINX_VERSION
FROM airglow923/nginx-boringssl:${NGINX_VERSION}

LABEL maintainer="Hyundeok Park <p.hyundeok76@gmail.com>"

COPY init-ngxblocker.sh /tmp

# curl: required by update-ngxblocker
# dig: optional dependency of scripts.d
RUN apk add --no-cache curl bind-tools
RUN su nginx -s /bin/sh -c "/tmp/init-ngxblocker.sh"
