FROM airglow923/nginx-boringssl:latest

LABEL maintainer="Hyundeok Park <p.hyundeok76@gmail.com>"

COPY init-ngxblocker.sh /tmp

RUN apk add --no-cache curl
# ngxblocker depends on dig
RUN apk add bind-tools
RUN /tmp/init-ngxblocker.sh
RUN apk del curl
